from datetime import datetime
from typing import Optional

from pydantic import BaseModel, ConfigDict, EmailStr, Field


class UserBase(BaseModel):
    first_name: Optional[str] = Field(default=None, max_length=100)
    last_name: Optional[str] = Field(default=None, max_length=100)
    middle_name: Optional[str] = Field(default=None, max_length=100)

    email: Optional[EmailStr] = Field(default=None, max_length=255)
    contact_number: Optional[str] = Field(default=None, max_length=20)

    username: Optional[str] = Field(default=None, max_length=50)
    role: Optional[str] = Field(default=None, max_length=50)
    employee_id: Optional[str] = Field(default=None, max_length=50)
    shift_type: str = Field(default="day", max_length=20)
    password_rotated_at: Optional[datetime] = Field(default=None)


class UserCreate(UserBase):
    first_name: str = Field(..., max_length=100)
    last_name: str = Field(..., max_length=100)

    email: EmailStr | None = Field(default=None, max_length=255)

    username: str = Field(..., max_length=50)
    password: Optional[str] = Field(default=None, min_length=6, max_length=255)
    
    role: str = Field(..., max_length=50)


class UserUpdate(UserBase):
    password: Optional[str] = Field(default=None, min_length=6, max_length=255)
    current_password: Optional[str] = Field(default=None)
    change_password: bool = Field(default=False)


class UserRead(UserBase):
    """Standard user read schema; sensitive fields are intentionally excluded."""

    model_config = ConfigDict(from_attributes=True)

    user_id: str
    is_deleted: bool


class GeneratedUserCredentialsRead(BaseModel):
    """Autogenerated credentials visible only to privileged admin actions."""

    one_time_login_password: str
    secondary_password: str | None = None


class UserCreateResultRead(BaseModel):
    """Create response payload that includes generated credentials when applicable."""

    user: UserRead
    generated_credentials: GeneratedUserCredentialsRead | None = None


class UserSecondaryPasswordRead(BaseModel):
    """Admin-only secondary password retrieval payload."""

    user_id: str
    secondary_password: str
    rotated_at: datetime | None = None


class UserLoginPasswordResetRequest(BaseModel):
    """Admin-only login password reset request gated by secondary password."""

    secondary_password: str = Field(..., min_length=8, max_length=255)


class UserLoginPasswordResetResultRead(BaseModel):
    """Admin-only login password reset payload for one-time credential handoff."""

    user_id: str
    generated_credentials: GeneratedUserCredentialsRead
    must_change_password: bool
